{% set name = "spm1d" %}
{% set version = "0.4.18" %}
{% set sha256 = "36a605f5461d96ff9d817666535f3bb028f0c8596ae05e68826f7fbeb7d7a8f1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - scipy
    - numpy
    - matplotlib-base

test:
  imports:
    - spm1d

about:
  home: http://www.spm1d.org/
  license: GPL-3.0
  license_file: LICENSE.txt
  # xref: https://github.com/0todd0000/spm1d/pull/57
  #license_file: LICENSE.txt
  summary: One-Dimensional Statistical Parametric Mapping in Python
  description: |
    spm1d uses Random Field Theory expectations regarding the behavior 
    of smooth, one-dimensional Gaussian fields to make statistical 
    inferences regarding a set of one-dimensional continua.
  doc_url: http://www.spm1d.org/Documentation.html
  dev_url: https://github.com/0todd0000/spm1d

extra:
  recipe-maintainers:
    - melund
