{% set name = "spm1d" %}
{% set version = "0.4.53" %}
{% set sha256 = "13163a8ae4e5d4c0c8f518432efaa1d7be30b4b09a976a600953ffab2599a4f8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - scipy
    - numpy
    - matplotlib-base

test:
  requires:
    - python {{ python_min }}
  imports:
    - spm1d

about:
  home: http://www.spm1d.org/
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: 'One-Dimensional Statistical Parametric Mapping in Python'
  description: |
    spm1d uses Random Field Theory expectations regarding the behavior 
    of smooth, one-dimensional Gaussian fields to make statistical 
    inferences regarding a set of one-dimensional continua.
  doc_url: http://www.spm1d.org/Documentation.html
  dev_url: https://github.com/0todd0000/spm1d

extra:
  recipe-maintainers:
    - melund
