travis:
  secure:
    BINSTAR_TOKEN: miB/bUcLi5Nn4fF1mFcoCUq/ispdqbiiojWb1hty6scGUIIrvNa4qzu7V0lxaNpmaUpTI2bgnZguBLzryxS4up9GaAEzthMi42RZlvsZd4HDPptOWKiswthvcatcwcQFz+a/fbkSFKUBnpsQ78jdnDdir2eHX976m/XfDsf0XWHTfV/peKDrDRCJ07/4ts6G8nAcOKm+pD1dvm0xPqp3wuO+mtieebtwjDXg2fg7PtKx9c79QgSCqra+lux/H9SgtbWKvJGDwAV5zxvHpwLkevvM/T+dzw2JRK+Da+5C+LNOk64E/kWt5kyqYYduaDSsmc4zR1K9bTIgiDxu7eZoGyoRoybeQ8PfrqmecA4a1nrUhQOx0twwbzwKcmG8V0Y36E/x3SFiA92wMOCqfrRdphiYdAnJDMpklQQACjWTHrfSp6/mejLNqZdw1DA2P7v19kXKfPpAiMgFs8VU9B00rnZrYOc6wdznnXMnhnhOck01DdUMogNY4wq+ORFyfKhXmvrqwk/UIhFJxxiUqxsiuHzyTNUlpZ8JiK3QazVNYgIefsF/Cy3pcD8OnweVF+OWIDOAY4YNJPxVBT0gqKnQuAiEWgLMrphqEw39Q7sJ4arfD8wf7AYK4xyxvkc4D1lh0X80blgFwedqrsC3JNWqpywaFFtYWO62pPI9+hHA/bM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
