travis:
  secure:
    BINSTAR_TOKEN: jTRpknu37vQTpFt86DAhOTud1sgHtAFHPz9egnB2+CcnbaDZmGpZR4u44avB34eoHdodmDBd9UAVJDfmzuAtiAMlbraeQDRo8pqz/C2iiH8YbJWqf2jpnVk7zQPBEII9pjBiodJgS1zqorCX4zCk79Idq7nZLQMnPCKLyuf7srGmLdJFm9MEcLuJE4nr+kH8Jsfs1ESqXrV4hmFgZjRLT4G53mdXyF1DOLbulYL/aDW5VBNG2a3G42FYPrkUGzrWex2wUaqjSD7ky4i189oKt99G/WodnF5qe85PaBOn6yGEIPaXPf6DGjJq8LOZaVf/pWFYcj1MHbfTnW8ViLa6d7oKxMbZMtvXlaISRNxpyPK1icqIIQOsk2C+yTwdzgyEi1BIvHgtJQmZij086yK1+9/C2GDJn4OBtaYGleHjYSaFHoxAPWCExlHMc6oyAR9S62cpqrSfp4huVBpBnAasWZsvxIFf+7j+AsGOleSd+orZjTPsGbSKIOxXPNXe30nfiyUyZ7iA9tuK42ttdp2nfDyo4wKaLAZnOBW8yqR910TsM/6aqWTaAKQedIr3kDwJIj8nNAi9XnzN7d9mWkZdxRBmzYjukKD2AbNd5MtmqVG1SR4+J5tZbx2S4UXuZzRPwKRgM9uEdphzA+GS0b5LJ6loUpFymwVSn1vU1gWoZb0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
